name: attendenace

'on': push

jobs:
    build:
        runs-on: ubuntu-latests
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: build with make
          run: make build
